import type { HotspotSeed } from '../../../types/explore.js'

/**
 * Curated candidates only; every item must pass Amap verification before use.
 * Official visit rules checked 2026-07-24:
 * https://www.dpm.org.cn/Visit.html and https://ticket.dpm.org.cn/
 */
export const BEIJING_HOTSPOTS: HotspotSeed[] = [
  {
    id: 'beijing-palace-museum',
    city: '北京',
    adcode: '110000',
    name: '故宫博物院',
    searchName: '故宫博物院',
    district: '东城区',
    category: 'landmark',
    reason: '北京中轴线最核心的一站，内容密度高，适合单独留出半天并提前预约。',
    tags: ['世界遗产', '博物馆', '需预约'],
    suitablePersonas: ['fast', 'couple', 'family'],
    suggestedDuration: '建议半天',
    bestTime: '上午入场',
    theme: 'museum',
    seedLng: 116.3972,
    seedLat: 39.9163,
    reservationNote: '故宫官方不售当日票，通常于参观前 7 日 20:00 开放预约；周一一般闭馆，法定节假日除外。',
  },
  {
    id: 'beijing-summer-palace',
    city: '北京',
    adcode: '110000',
    name: '颐和园',
    searchName: '颐和园',
    district: '海淀区',
    category: 'nature',
    reason: '园林、湖景和古建集中，适合把半天留给一个完整区域，不必跨城赶场。',
    tags: ['皇家园林', '湖景', '古建'],
    suitablePersonas: ['couple', 'family', 'lazy'],
    suggestedDuration: '建议半天',
    bestTime: '上午或日落前',
    theme: 'garden',
    seedLng: 116.2733,
    seedLat: 39.9999,
  },
  {
    id: 'beijing-universal',
    city: '北京',
    adcode: '110000',
    name: '北京环球度假区',
    searchName: '北京环球度假区',
    district: '通州区',
    category: 'theme_park',
    reason: '适合直接占满一天的主目的地，不建议再拼接市中心景点。',
    tags: ['主题乐园', '一日游', '亲子'],
    suitablePersonas: ['fast', 'couple', 'family'],
    suggestedDuration: '建议一整天',
    bestTime: '开园前抵达',
    theme: 'wonderland',
    seedLng: 116.6739,
    seedLat: 39.8567,
  },
  {
    id: 'beijing-qianmen',
    city: '北京',
    adcode: '110000',
    name: '前门大街—大栅栏',
    searchName: '前门大街',
    district: '东城区',
    category: 'street',
    reason: '老字号、传统商业和中轴线氛围集中，可与天坛或故宫南线自然衔接。',
    tags: ['步行街', '老字号', '中轴线'],
    suitablePersonas: ['fast', 'family', 'urban'],
    suggestedDuration: '建议 2 小时',
    bestTime: '下午至亮灯',
    theme: 'market',
    seedLng: 116.3977,
    seedLat: 39.8990,
  },
  {
    id: 'beijing-shichahai',
    city: '北京',
    adcode: '110000',
    name: '什刹海—烟袋斜街',
    searchName: '什刹海',
    district: '西城区',
    category: 'district',
    reason: '湖面、胡同和老城生活感共存，适合午后慢走到夜色。',
    tags: ['胡同', '湖景', '老北京'],
    suitablePersonas: ['couple', 'lazy', 'urban'],
    suggestedDuration: '建议 2–3 小时',
    bestTime: '午后至晚间',
    theme: 'river',
    seedLng: 116.3890,
    seedLat: 39.9410,
  },
  {
    id: 'beijing-798',
    city: '北京',
    adcode: '110000',
    name: '798艺术区',
    searchName: '798艺术区',
    district: '朝阳区',
    category: 'district',
    reason: '展览、工业建筑和店铺密集，更适合看当期内容后在一个街区内自由组合。',
    tags: ['艺术区', '展览', '工业建筑'],
    suitablePersonas: ['couple', 'lazy', 'urban'],
    suggestedDuration: '建议 3 小时',
    bestTime: '午后',
    theme: 'city',
    seedLng: 116.4970,
    seedLat: 39.9840,
    indoorFriendly: true,
  },
  {
    id: 'beijing-olympic-forest',
    city: '北京',
    adcode: '110000',
    name: '奥林匹克森林公园',
    searchName: '奥林匹克森林公园',
    district: '朝阳区',
    category: 'nature',
    reason: '大面积绿地适合跑步、遛娃和放空，可与鸟巢水立方组成北中轴半日线。',
    tags: ['公园', '户外', '亲子'],
    suitablePersonas: ['family', 'lazy'],
    suggestedDuration: '建议 2–3 小时',
    bestTime: '清晨或傍晚',
    theme: 'garden',
    seedLng: 116.3920,
    seedLat: 40.0150,
  },
  {
    id: 'beijing-sanlitun',
    city: '北京',
    adcode: '110000',
    name: '三里屯太古里',
    searchName: '三里屯太古里',
    district: '朝阳区',
    category: 'mall',
    reason: '购物、餐饮与夜生活集中，适合不想频繁换乘的城市型半天。',
    tags: ['商场', '夜生活', '潮流'],
    suitablePersonas: ['couple', 'lazy', 'urban'],
    suggestedDuration: '建议 2–4 小时',
    bestTime: '下午至晚间',
    theme: 'city',
    seedLng: 116.4550,
    seedLat: 39.9330,
    indoorFriendly: true,
  },
  {
    id: 'beijing-wangfujing',
    city: '北京',
    adcode: '110000',
    name: '王府井步行街',
    searchName: '王府井步行街',
    district: '东城区',
    category: 'street',
    reason: '商业与核心景点距离近，适合作为故宫东侧或国家博物馆之后的晚间落点。',
    tags: ['步行街', '购物', '夜景'],
    suitablePersonas: ['fast', 'family', 'urban'],
    suggestedDuration: '建议 1–2 小时',
    bestTime: '傍晚',
    theme: 'night',
    seedLng: 116.4120,
    seedLat: 39.9150,
  },
  {
    id: 'beijing-national-museum',
    city: '北京',
    adcode: '110000',
    name: '中国国家博物馆',
    searchName: '中国国家博物馆',
    district: '东城区',
    category: 'landmark',
    reason: '大型室内文化目的地，适合雨天或高温天，并需要按官方要求提前预约。',
    tags: ['博物馆', '室内', '需预约'],
    suitablePersonas: ['fast', 'family', 'lazy', 'urban'],
    suggestedDuration: '建议 3–4 小时',
    bestTime: '上午',
    theme: 'museum',
    seedLng: 116.4070,
    seedLat: 39.9050,
    indoorFriendly: true,
  },
  {
    id: 'beijing-guijie',
    city: '北京',
    adcode: '110000',
    name: '簋街',
    searchName: '簋街',
    district: '东城区',
    category: 'food',
    reason: '餐饮密集且营业时段偏晚，更适合做夜游路线的用餐落点。',
    tags: ['美食街', '夜宵', '胡同周边'],
    suitablePersonas: ['fast', 'couple', 'urban'],
    suggestedDuration: '建议 1–2 小时',
    bestTime: '晚餐至夜宵',
    theme: 'night',
    seedLng: 116.4220,
    seedLat: 39.9470,
  },
  {
    id: 'beijing-happy-valley',
    city: '北京',
    adcode: '110000',
    name: '北京欢乐谷',
    searchName: '北京欢乐谷',
    district: '朝阳区',
    category: 'theme_park',
    reason: '项目型目的地，适合亲子或朋友把大半天集中留在园区。',
    tags: ['主题乐园', '游乐设施', '亲子'],
    suitablePersonas: ['fast', 'couple', 'family'],
    suggestedDuration: '建议半天至一天',
    bestTime: '开园后',
    theme: 'wonderland',
    seedLng: 116.5010,
    seedLat: 39.8660,
  },
]
