import type { HotspotSeed } from '../../../types/explore.js'

/**
 * Curated candidates only; every item must pass Amap verification before use.
 * Official venue information checked 2026-07-24:
 * https://www.lzmuseum.cn/ and https://www.songcn.com/park/1
 */
export const HANGZHOU_HOTSPOTS: HotspotSeed[] = [
  {
    id: 'hangzhou-west-lake',
    city: '杭州',
    adcode: '330100',
    name: '西湖风景名胜区',
    searchName: '西湖风景名胜区',
    district: '西湖区',
    category: 'landmark',
    reason: '杭州最难绕开的核心体验，点位很多，适合按湖滨、苏堤或北山街分段游玩。',
    tags: ['世界遗产', '湖景', '城市地标'],
    suitablePersonas: ['fast', 'couple', 'family', 'lazy'],
    suggestedDuration: '建议半天',
    bestTime: '清晨或傍晚',
    theme: 'river',
    seedLng: 120.1450,
    seedLat: 30.2450,
  },
  {
    id: 'hangzhou-lingyin',
    city: '杭州',
    adcode: '330100',
    name: '灵隐寺—飞来峰',
    searchName: '灵隐寺',
    district: '西湖区',
    category: 'landmark',
    reason: '寺院、石刻和山林集中，适合上午慢游，并预留排队和步行时间。',
    tags: ['寺院', '山林', '人文'],
    suitablePersonas: ['couple', 'family', 'lazy'],
    suggestedDuration: '建议 3 小时',
    bestTime: '上午',
    theme: 'garden',
    seedLng: 120.1021,
    seedLat: 30.2432,
  },
  {
    id: 'hangzhou-xixi',
    city: '杭州',
    adcode: '330100',
    name: '西溪国家湿地公园',
    searchName: '西溪国家湿地公园',
    district: '西湖区',
    category: 'nature',
    reason: '水网、芦苇和慢行空间适合放慢节奏，最好单独安排半天。',
    tags: ['湿地', '自然', '亲子'],
    suitablePersonas: ['couple', 'family', 'lazy'],
    suggestedDuration: '建议半天',
    bestTime: '上午',
    theme: 'garden',
    seedLng: 120.0650,
    seedLat: 30.2690,
  },
  {
    id: 'hangzhou-liangzhu-museum',
    city: '杭州',
    adcode: '330100',
    name: '良渚博物院',
    searchName: '良渚博物院',
    district: '余杭区',
    category: 'landmark',
    reason: '了解良渚文明的高密度室内目的地，适合雨天，并应提前查看预约要求。',
    tags: ['博物馆', '良渚文化', '室内'],
    suitablePersonas: ['family', 'lazy', 'urban'],
    suggestedDuration: '建议 2–3 小时',
    bestTime: '上午',
    theme: 'museum',
    seedLng: 120.0550,
    seedLat: 30.3940,
    indoorFriendly: true,
    reservationNote: '良渚博物院实行网络实名预约，通常周一闭馆；请以官方最新参观须知为准。',
  },
  {
    id: 'hangzhou-songcheng',
    city: '杭州',
    adcode: '330100',
    name: '杭州宋城',
    searchName: '杭州宋城',
    district: '西湖区',
    category: 'theme_park',
    reason: '演出和园区内容适合占据大半天，具体场次以景区当天公告为准。',
    tags: ['主题景区', '演出', '亲子'],
    suitablePersonas: ['fast', 'couple', 'family'],
    suggestedDuration: '建议半天至一天',
    bestTime: '结合演出场次',
    theme: 'wonderland',
    seedLng: 120.1020,
    seedLat: 30.1600,
    reservationNote: '园区项目和演出场次可能因天气、现场安排调整，请出发前查看杭州宋城官方当天节目单。',
  },
  {
    id: 'hangzhou-xiaohe-street',
    city: '杭州',
    adcode: '330100',
    name: '小河直街历史文化街区',
    searchName: '小河直街历史文化街区',
    district: '拱墅区',
    category: 'district',
    reason: '运河边的老街尺度舒适，适合和桥西、拱宸桥组合成慢逛路线。',
    tags: ['运河', '老街', '散步'],
    suitablePersonas: ['couple', 'lazy', 'urban'],
    suggestedDuration: '建议 2 小时',
    bestTime: '午后',
    theme: 'lane',
    seedLng: 120.1420,
    seedLat: 30.3190,
  },
  {
    id: 'hangzhou-hefang-street',
    city: '杭州',
    adcode: '330100',
    name: '清河坊历史文化特色街区',
    searchName: '清河坊历史文化特色街区',
    district: '上城区',
    category: 'street',
    reason: '传统商业、老字号和南宋街巷氛围集中，可与吴山一带顺路组合。',
    tags: ['步行街', '老字号', '南宋文化'],
    suitablePersonas: ['fast', 'family', 'urban'],
    suggestedDuration: '建议 2 小时',
    bestTime: '下午至晚间',
    theme: 'market',
    seedLng: 120.1730,
    seedLat: 30.2413,
  },
  {
    id: 'hangzhou-hubin-intime',
    city: '杭州',
    adcode: '330100',
    name: '湖滨银泰in77',
    searchName: '湖滨银泰in77',
    district: '上城区',
    category: 'mall',
    reason: '购物餐饮与西湖东岸相连，雨天也能在室内外之间灵活切换。',
    tags: ['商圈', '西湖边', '室内'],
    suitablePersonas: ['couple', 'lazy', 'urban'],
    suggestedDuration: '建议 2–4 小时',
    bestTime: '下午至晚间',
    theme: 'city',
    seedLng: 120.1620,
    seedLat: 30.2560,
    indoorFriendly: true,
  },
  {
    id: 'hangzhou-longjing-village',
    city: '杭州',
    adcode: '330100',
    name: '龙井村',
    searchName: '龙井村',
    district: '西湖区',
    category: 'district',
    reason: '茶园和山路构成区别于湖滨的杭州体验，适合天气舒适时慢走。',
    tags: ['茶园', '山路', '村落'],
    suitablePersonas: ['couple', 'lazy', 'urban'],
    suggestedDuration: '建议 2–3 小时',
    bestTime: '上午或午后',
    theme: 'garden',
    seedLng: 120.1030,
    seedLat: 30.2240,
  },
  {
    id: 'hangzhou-grand-canal',
    city: '杭州',
    adcode: '330100',
    name: '京杭大运河杭州景区—拱宸桥',
    searchName: '拱宸桥',
    district: '拱墅区',
    category: 'landmark',
    reason: '桥、运河和周边博物馆群可以串成完整半日线，雨天也有室内备选。',
    tags: ['大运河', '古桥', '博物馆群'],
    suitablePersonas: ['fast', 'family', 'urban'],
    suggestedDuration: '建议半天',
    bestTime: '下午',
    theme: 'river',
    seedLng: 120.1420,
    seedLat: 30.3200,
  },
  {
    id: 'hangzhou-wulin-night-market',
    city: '杭州',
    adcode: '330100',
    name: '武林夜市',
    searchName: '武林夜市',
    district: '拱墅区',
    category: 'food',
    reason: '更适合作为市中心夜游的用餐和逛摊落点，而不是白天专程前往。',
    tags: ['夜市', '小吃', '市中心'],
    suitablePersonas: ['fast', 'couple', 'urban'],
    suggestedDuration: '建议 1–2 小时',
    bestTime: '晚间',
    theme: 'night',
    seedLng: 120.1630,
    seedLat: 30.2650,
  },
  {
    id: 'hangzhou-xianghu',
    city: '杭州',
    adcode: '330100',
    name: '湘湖国家旅游度假区',
    searchName: '湘湖国家旅游度假区',
    district: '萧山区',
    category: 'nature',
    reason: '湖岸空间比市中心更舒展，适合骑行、遛娃或留出半天放空。',
    tags: ['湖景', '骑行', '亲子'],
    suitablePersonas: ['family', 'lazy', 'couple'],
    suggestedDuration: '建议半天',
    bestTime: '上午或傍晚',
    theme: 'river',
    seedLng: 120.2340,
    seedLat: 30.1400,
  },
]
